In [1]:
import numpy as np

In [2]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
add=arr1+arr2
print(add)

[ 7  9 11 13  8]


In [3]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
mul=arr1*arr2
print(mul)

[ 6 14 24 36 15]


In [5]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
sub=arr2-arr1
print(sub)

[ 5  5  5  5 -2]


In [7]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
div=arr2//arr1
print(div)

[6 3 2 2 0]


In [9]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
que=arr1%arr2
print(que)

[1 2 3 4 2]


In [10]:
arr1=np.array([1, 2, 3, 4, 5])
arr2=np.array([6,7,8,9,3])
squ=arr1**arr2
print(squ)

[     1    128   6561 262144    125]


In [ ]:
Numpy is for fast operations on arrays, including mathematical,logical and basic statistical operations.firstly import numpy create two arrays and perform basic mathematical operations on them.
operations such as addition,multiplication,subtraction,division,modulus,square